### PR TITLE
I created a jQuery plugin :D

### PR DESCRIPTION
**Pull request by TejasQ**
Hi, I created a jQuery plugin with some options based on your project. :) 

I got rid of the 'css' folder because options are specified through jQuery, and I got rid of the license file because... well, open-source is awesome. I also moved the js into a js folder that is referenced in the html file instead for more organization. The js folder has two js files: one minifed, one fullsize for development.

I hope this is okay!

### CODE REVIEW

**Comment by TejasQ** [comment]
GAH, I wanted to merge this not into your master but perhaps a different branch! Closing the request!

**Comment by TejasQ** [comment]
Well, you don't have another branch, so... let's see what you have to say :)

**Comment by alexgibson** [comment]
Umm... feel free to fork this repo and do what you like with it :)

Thanks for the pull request, but... I don't see why this demo needs jQuery to be quite honest? You have added a large dependency to the project, when you could probably quite easily turn it into a vanilla JS plugin in just a few bytes. You have also added a bunch in inline JS and CSS in the HTML file, which is not ideal.

Finally, removing the MIT license because you do not understand why it is important is not ok, sorry!

**Comment by TejasQ** [comment]
I just thought the users would like to have the option. To be honest, I'm new to github, so I don't quite know what I'm doing. Thanks for your response. Have a great day!

**Comment by alexgibson** [comment]
That's ok, thanks for the PR!

If you feel like addressing the comments above and submitting a new PR, feel free.

**Pull request closed without merging**
